import { useEffect, useMemo, useState } from 'react';
import { getTreeholeStatus, sealTreehole, unlockTreehole } from '../../api/client';
import '../growth/GrowthView.css';
import './TreeholeView.css';

interface Capsule {id:string;created_at:string;unlock_date:string}
function futureDate(months:number){const d=new Date();d.setMonth(d.getMonth()+months);const offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,16);}
function TreeholeView(){
 const [content,setContent]=useState('');const [password,setPassword]=useState('');const [unlockDate,setUnlockDate]=useState(futureDate(6));const [mode,setMode]=useState<'comfort'|'listen'>('listen');const [cloudConsent,setCloudConsent]=useState(false);const [capsules,setCapsules]=useState<Capsule[]>([]);const [answer,setAnswer]=useState('');const [busy,setBusy]=useState(false);const [openId,setOpenId]=useState('');const [openPassword,setOpenPassword]=useState('');const [revealed,setRevealed]=useState('');const [error,setError]=useState('');
 const load=()=>getTreeholeStatus().then(r=>setCapsules((r as {items:Capsule[]}).items));useEffect(()=>{load().catch(()=>{});},[]);
 const seal=async()=>{if(!content.trim()||password.length<6||(mode==='comfort'&&!cloudConsent))return;setBusy(true);setError('');try{const r=await sealTreehole({content,password,unlock_date:new Date(unlockDate).toISOString(),response_mode:mode,cloud_consent:cloudConsent}) as {answer:string};setContent('');setPassword('');setCloudConsent(false);setAnswer(r.answer);await load();}catch(e){setError(e instanceof Error?friendlyError(e.message):'封存失败');}finally{setBusy(false);}};
 const open=async()=>{setError('');setRevealed('');try{const r=await unlockTreehole({id:openId,password:openPassword}) as {content:string};setRevealed(r.content);setOpenPassword('');}catch(e){setError(e instanceof Error?friendlyError(e.message):'无法解锁');}};
 const next=useMemo(()=>capsules.find(item=>new Date(item.unlock_date)>new Date()),[capsules]);
 return <main className="treehole-page"><section className="treehole-hero"><span>ENCRYPTED TIME CAPSULE</span><h2>加密树洞</h2><p>说完就让它离开屏幕。到约定的那天之前，正确密码也无法打开。</p><div className="treehole-security"><b>AES-256-GCM</b><span>密码不会保存</span><span>不进入聊天归档与记忆</span><span>系统时间回退保护</span></div></section>
 <section className="treehole-layout"><article className="treehole-seal"><header><h3>此刻想留下的话</h3><div><button className={mode==='listen'?'is-active':''} onClick={()=>{setMode('listen');setCloudConsent(false);}}>纯本地封存</button><button className={mode==='comfort'?'is-active':''} onClick={()=>setMode('comfort')}>AI 温柔回应</button></div></header><div className={`treehole-privacy ${mode==='listen'?'is-local':'is-cloud'}`}><b>{mode==='listen'?'完全本地':'需要发送至 DeepSeek'}</b><span>{mode==='listen'?'内容只用于本机加密，不会发送给模型。':'内容会发送给 DeepSeek 生成一次安慰回复，但不会进入本地聊天归档或记忆。'}</span></div><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="这里的文字只会短暂出现在屏幕上…"/><div className="treehole-fields"><label><span>解锁时间</span><input type="datetime-local" min={futureDate(0)} value={unlockDate} onChange={e=>setUnlockDate(e.target.value)}/><small><button onClick={()=>setUnlockDate(futureDate(6))}>半年</button><button onClick={()=>setUnlockDate(futureDate(12))}>一年</button></small></label><label><span>封存密码（至少 6 位）</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" placeholder="请牢记，无法找回"/></label></div>{mode==='comfort'&&<label className="treehole-consent"><input type="checkbox" checked={cloudConsent} onChange={e=>setCloudConsent(e.target.checked)}/><span>我明确同意将本次输入发送至 DeepSeek，以生成安慰回复。</span></label>}<button className="treehole-primary treehole-seal-button" disabled={busy||!content.trim()||password.length<6||(mode==='comfort'&&!cloudConsent)} onClick={seal}>{busy?'正在加密封存…':'封存并从屏幕抹去'}</button>{answer&&<div className="treehole-answer"><i>✦</i><p>{answer}</p></div>}</article>
 <aside className="treehole-vault"><header><span><small>已封存</small><strong>{capsules.length}</strong></span>{next&&<p>下一次可解锁<br/><b>{new Date(next.unlock_date).toLocaleString()}</b></p>}</header><div className="capsule-list">{capsules.map(item=>{const locked=new Date(item.unlock_date)>new Date();return <button key={item.id} onClick={()=>setOpenId(item.id)} className={openId===item.id?'is-active':''}><i>{locked?'⌛':'✦'}</i><span><strong>{locked?'沉睡中':'可以打开'}</strong><small>{new Date(item.unlock_date).toLocaleDateString()}</small></span></button>})}</div>{openId&&<div className="unlock-box"><input type="password" value={openPassword} onChange={e=>setOpenPassword(e.target.value)} placeholder="输入封存密码"/><button onClick={open}>尝试解锁</button></div>}{error&&<p className="treehole-error">{error}</p>}</aside></section>
 {revealed&&<section className="treehole-revealed"><header><b>来自过去的你</b><button onClick={()=>setRevealed('')}>重新合上</button></header><p>{revealed}</p><small>内容仍以密文保存，下次查看仍需密码。</small></section>}
 </main>;
}
function friendlyError(message:string){if(message.includes('423'))return '还没到约定的解锁时间。让它再安静地睡一会儿。';if(message.includes('429'))return '密码尝试次数过多，已暂时锁定 15 分钟。';if(message.includes('409'))return '检测到系统时间明显回退。请恢复正确时间后再试。';if(message.includes('400'))return '请求未通过：请检查密码或云端授权选项。';return message;}
export default TreeholeView;
